### PR TITLE
WP-69: Added linter

### PR DESCRIPTION
**Pull request by PredatorFeesh**

### CODE REVIEW

**Comment by PredatorFeesh** [comment]
@watchpartyappmain @ian-s-mcb requested review in case we want any rules ignored, this shouldn't be enforcing any style, only "workability"

**Comment by usersblock** [comment]
LGTM

**Review by usersblock — APPROVED** [review]
This shouldn't interfere with anything we already have.

**Review by ian-s-mcb — APPROVED** [review]
Not sure how GitHub actions work, but I think @PredatorFeesh got it to work in the end.

**Review by amckoy42 — APPROVED** [review]
I, for one, welcome our new ESLint overlord.

**Pull request merged**
