### PR TITLE
wp-94 / wp-128 - changed path and added chromedriver

### PR DESCRIPTION
**Pull request by shahan27**
simple change 👍

### CODE REVIEW

**Comment by PredatorFeesh** [comment]
Interesting that it says it conflicts.. I think my revert didin't actually take effect. No matter hopefully easy fix.

**Comment by PredatorFeesh** [comment]
Don't forget to add the ticket number to the title of this PR

**Comment by PredatorFeesh** [comment]
Just a note: This is part of 2 stories, because the first part (wp-94) was already finished. This is improvements and fixes done to that, in conjunction to improvements specified by wp-128

**Comment by shahan27** [comment]
@PredatorFeesh Test Complete 

Screen Shot 2020-05-08 at 1 04 26 AM

**Comment by PredatorFeesh** [comment]
I'm getting another weird error when running this twice the chrome driver is used even after the program terminates `OSError: [Errno 26] Text file busy: 'path/to/driver/chromedriver'`.. this can be fixed locally if I just `lsof` for the PID and kill the process, but I'm not sure if this is a recurring issue

**Comment by PredatorFeesh** [comment]
Other than that the 4 tests were successful for me :+1:

**Review by PredatorFeesh — APPROVED** [review]

**Comment by PredatorFeesh** [comment]
What's left of this PR: Make test location conditional on the env

**Pull request merged**
