### PR TITLE
Wp 45 create GET endpoints 

### PR DESCRIPTION
**Pull request by usersblock**
Created GET endpoints
Created all models of database

### CODE REVIEW

**Comment by ian-s-mcb** [comment]
@rxkt Semicolons are optional in JS and a lot of people prefer to omit them.

We haven't chosen a style guide and linter, but we should. The style guide I tend to use is called Standard, and requires that semi-colons are absent. Airbnb is another common style guide, but it does require semi-colons. I'd leave the style corrections to the linter because doing it by hand is tedious.

https://github.com/standard/standard
https://github.com/airbnb/javascript

**Comment by ian-s-mcb** [comment]
@usersblock Your commits don't start off and build onto the backend code I wrote. Instead, it removes it. Could you make new commits that continue with the code we have?

**Comment by usersblock** [comment]
@rxkt I think the issue is okay for now since we still need to decide on a universal format. Otherwise, no errors have occurred.

**Comment by usersblock** [comment]
@ian-s-mcb I reverted the delete and made changes to the name of users as well as added a few more columns.

**Comment by usersblock** [comment]
@ian-s-mcb 
- The dotenv line has been removed
- Movie has been changed
- For Movie item, there's no need for an enumerator for only 3 states. The watched parameter can be set to 0 - Not Watched 1 -  Watched 2 - Not interested
- Permission was removed since it's no longer planned
- Recommovie/Recommsysfeedback/requestrecommendations/Sublist have been moved to a sub-folder in models since those features can be implemented in the future based on user stories. This will not interfere with sync().

**Pull request closed without merging**
