### PR TITLE
setting up backend deploy too

### PR DESCRIPTION
**Pull request by watchpartyappmain**

### CODE REVIEW

**Review by PredatorFeesh — APPROVED** [review]

**Comment by PredatorFeesh** [comment]
Should we add `--force` to our push in case heroku decides to do any funny stuff again?

**Comment by watchpartyappmain** [comment]
forcing push in GA due to random heroku changes to repo

**Comment by PredatorFeesh** [comment]
Looks good to merge :+1:

**Comment by PredatorFeesh** [comment]
Now comes the prayer part :pray:

**Pull request merged**
