### PR TITLE
WP-88 add follow methods

### PR DESCRIPTION
**Pull request by usersblock**

### CODE REVIEW

**Comment by ian-s-mcb** [comment]
Somehow changes to our GitHub Actions got bundled into this PR. I'm not sure if @PredatorFeesh and @rxkt want them. Maybe you make a new PR without that change. Also, you want to use `.prototype` in these methods, just like with the Movie model.

**Comment by usersblock** [comment]
Prototype is only meant for use on single instances. Without it, the function can be applied to an entire class, without needing to find/create an instance.

**Comment by usersblock** [comment]
Also fixed the unintended changes

**Comment by ian-s-mcb** [comment]
With the changes to User model in #76, this PR isn't needed any more. @usersblock green lighted #76 when we talked on Slack, so I think we're ready to close this PR.

**Comment by PredatorFeesh** [comment]
Closing this PR :+1:

**Pull request closed without merging**
