### PR TITLE
Wp 43 login template

### PR DESCRIPTION
**Pull request by shahan27**
Add all the files needed to run Ios and Android builds. This includes starter code for the login screen. 

signupscreen

### CODE REVIEW

**Comment by G-Andrey** [comment]
got it to work on my android after god knows how long trying to set it up. Looks good

**Comment by shahan27** [comment]
Routing has been setup with 4 pages and included Overview and watched page.

**Comment by ian-s-mcb** [comment]
Could you help me out, @shahan27. I'm having trouble viewing the mobile app. I ran `npm install && npm run web` in the mobile folder and I got the following error:

```
Failed to compile

/mnt/storage/school/ccny_2020-s/csc-topics_sw_engin/repo/WatchParty/mobile/node_modules/react-router-native/NativeRouter.js 11:9
Module parse failed: Unexpected token (11:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| function NativeRouter(props) {
>   return <MemoryRouter {...props} />;
| }
|
```

**Comment by PredatorFeesh** [comment]
Does testing still work in this commit? I see a lot of tests in `package.json` removed

**Comment by PredatorFeesh** [comment]
Can we move the files where code is implemented to `src`

**Comment by PredatorFeesh** [comment]
> Could you help me out, @shahan27. I'm having trouble viewing the mobile app. I ran `npm install && npm run web` in the mobile folder and I got the following error:
> 
> ```
> Failed to compile
> 
> /mnt/storage/school/ccny_2020-s/csc-topics_sw_engin/repo/WatchParty/mobile/node_modules/react-router-native/NativeRouter.js 11:9
> Module parse failed: Unexpected token (11:9)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |  */
> | function NativeRouter(props) {
> >   return <MemoryRouter {...props} />;
> | }
> |
> ```

I'm also getting this exact same issue btw ^^
I'm working on this locally, I fixed jest and moved the files around. Will push soon, sadly it's a big ugly commit.

**Comment by shahan27** [comment]
Yeah sorry guys I'm looking into the problems still.

**Pull request closed without merging**
