### PR TITLE
WP-95 - Remove lint in backend (22 errors)

### PR DESCRIPTION
**Pull request by ian-s-mcb**
backend_lint

### CODE REVIEW

**Review by usersblock — COMMENTED** [review]
This is likely fine when viewed from a file, but why are some of the datatypes unaligned?

**Comment by ian-s-mcb** [comment]
@usersblock That's because when the linter was added to backend by @PredatorFeesh , no style guide was specified. Instead, the corrections in this PR are very basic style issues that are caught by the default lint settings. I didn't realize that the linter was misconfigured until PR #49.

**Comment by usersblock** [comment]
In that case, it should be fine.

**Review by usersblock — APPROVED** [review]

**Comment by PredatorFeesh** [comment]
We could configure it to enforce a style, I thought might not be as necessary for the backend for a style enforcement but we could enforce a style

**Comment by PredatorFeesh** [comment]
^^ I see we have another PR for this, very nice :)

**Pull request merged**
